#!/usr/bin/env bash

# Load 
source "$(dirname "${BASH_SOURCE[0]}")/tools/brew-dual-utility"

# Define Homebrew paths
brew_dual_upgrade() {

    # Loop through all package arguments
    for PACKAGE in "$@"; do
        color_echo "INFO" "🔍 Checking $PACKAGE..."

        # Upgrade package on ARM Homebrew if installed
        if is_installed "$ARM_BREW" "$PACKAGE" "$ARM_ARCH"; then
            color_echo "INFO" "📦 Upgrading $PACKAGE on ARM Homebrew..."
            if [ "$VERBOSE" = true ]; then
                $ARM_ARCH "$ARM_BREW" upgrade -v "$PACKAGE"
            else
                $ARM_ARCH "$ARM_BREW" upgrade "$PACKAGE"
            fi

            color_echo "INFO" "✅ Successfully upgraded $PACKAGE on ARM Homebrew!"
        else
            
            color_echo "WARN" "⚠️ $PACKAGE is not installed on ARM Homebrew. Skipping..."
        fi

        # Update package on X86 Homebrew if installed
        if is_installed "$X86_BREW" "$PACKAGE" "$X86_ARCH"; then
            color_echo "INFO" "📦 Upgrading $PACKAGE on x86 Homebrew..."
            if [ "$VERBOSE" = true ]; then
                $X86_ARCH "$X86_BREW" upgrade -v "$PACKAGE"
            else
                $X86_ARCH "$X86_BREW" upgrade "$PACKAGE"
            fi

            color_echo "INFO" "✅ Successfully upgraded $PACKAGE on x86 Homebrew!"
        else
            color_echo "WARN" "⚠️ $PACKAGE is not installed on x86 Homebrew. Skipping..."
        fi
    done

    color_echo "INFO" "🎉 All package upgrade complete!"
}
